278-documentación proyecto front
ISPP-G5/NexONG pull request #303
Opened 2024-05-02 06:55 UTC by claugp06

In this PR, the documentation of the proyect for the frontend part has been created.

2024-05-02 20:07 UTC, auroranavas requested changes
I think you did a wonderful job putting all of this information together and I can tell you put a lot of effort 👏. Don't get scared by the number of comments! It's 90% typos. In general, check the correct styling of punctuation, for example, spaces after commas or periods.

2024-05-02 20:07 UTC, auroranavas commented on PPL/5-Proyect-Documentation-Frontend.md
> +- Añadir un dialogo con la información del educador de su hijo (igual que esta hecho en educadores que ve las familias pero a la inversa, las familias ven los datos de los educadores)
Dar un poco de contexto, parece que estás hablando del hijo del educador. Poner algo como "Que las familias puedan ver los datos de contacto de los educadores de sus hijos".

2024-05-02 20:07 UTC, auroranavas commented on PPL/5-Proyect-Documentation-Frontend.md
> +- En el primer feedback recibido, se proporciono la sugerencia de que en las pantalla (iniciando sesión como administrador) de socios y educadores la creación de asambleas y el añadir educadores de m
¿El feedback se tuvo en cuenta o no? En la frase final dices que se ha tenido en cuenta pero está en este apartado de mejoras. Es contradictorio.

2024-05-03 11:05 UTC, auroranavas requested changes
Thank you for taking the feedback into account, however, there is still stuff you didn't correct. I unresolved every comment you missed. Also, the title of the file is in Spanglish, if it's in English it should be `5-Project-Documentation-Frontend`.

2024-05-03 11:05 UTC, auroranavas commented on PPL/5-Proyect-Documentation-Frontend.md
> +Somos autocríticos de nuestro propio trabajo sabiendo y siendo conscientes de que siempre habrá cosas que se pueda mejorar para hacer las más accesibles. No solo se tiene esta autoevaluación en cuent
"... y que no **funcionaba** como se esperaba."

2024-05-03 13:00 UTC, claugp06 commented
> `5-Project-Documentation-Frontend`.

Most of them I had fixed them but I did not save the file, my bad. Now everything should be ok and if not just say so I can fix it

2024-05-05 16:27 UTC, auroranavas approved these changes
Thank you for taking the feedback into account. You did a really good job with this! 🙌

2024-05-05 16:34 UTC, auroranavas approved these changes

2024-05-05 16:34 UTC, merged