321-business plan
ISPP-G5/NexONG pull request #340
Opened 2024-05-11 10:47 UTC by FelixoGudiel

Investor section improved. Return rate diminished and more information about the procedence of these benefits added.

2024-05-13 15:52 UTC, pabpercab1 reviewed
En el documento se habla varias veces de los beneficios, son realmente estos números de los beneficios (ingresos-costes) o son solo ingresos?

2024-05-13 15:52 UTC, pabpercab1 commented on WPL/Business-plan.md
> +| **Beneficios** |**Ingreso/mes**| **Ingresos a los 2 años**|
En varios puntos se usa la palabra beneficio y en otras ingresos, la tabla muestra entonces los beneficios (ingresos-costes) o solo los ingresos?

2024-05-13 15:52 UTC, pabpercab1 commented on WPL/Business-plan.md
> +A partir de los análisis de costes y beneficios, obtenemos estas estimaciones:
Aqui también se menciona.

2024-05-13 15:52 UTC, pabpercab1 commented on WPL/Business-plan.md
> +Usando estas estimaciones podemos crear un gráfico que compara los costes que se acaban de mostrar con los posibles ingresos a recibir.
Sin embargo aqui se habla de ingreso

2024-05-13 16:43 UTC, JuanluRM commented
Gracias por tu aportación. La idea de la sección de inversión es comparar los ingresos con los costes para que los posibles socios tengan una estimación en la que basar su decisión, por tanto, se habla todo en ingresos y costes asi que he cambiado todo a ingresos para que se entienda mejor como habias propuesto.

2024-05-13 16:57 UTC, pabpercab1 approved these changes
Con este último cambio parece que esta todo bien. Buen trabajo @JuanluRM @FelixoGudiel !

2024-05-15 08:56 UTC, pabpercab1 requested changes
Después de reunirme con Marta para aclarar el anuncio de inversores, hemos llegado a la conclusión de que sigue faltando cierta información.

NexONG va a verderse por acciones o porcentaje de participación en la empresa? Va s tener otro modelo? En ese caso cuantas acciones y a cuanto cada acción? Si no, cuanto es la máxima inversión que se permite, cuantos inversores?

2024-05-16 10:20 UTC, JuanluRM commented
Buenas @pabpercab1, tras tu feedback se han hecho algunos cambios para aclarar el apartado. Pretendemos ser una sociedad limitada y por tanto nos venderemos por porcentaje de participación y los socios podrán además poner prima de emisión. Todos los detalles que responden a tus preguntas están incluidas en el documento.
Por último, se ha decidido quitar la tabla en la sección ya que resulta ser la tabla de costes e ingresos que se hablan en el documento de cálculo de los costes por lo que resulta redundante para esta sección de socios.

2024-05-18 11:28 UTC, pabpercab1 commented on WPL/Business-plan.md
> +Los socios que decidan invertir en NexONG obtendrán un retorno de inversión del 25% anual, calculado sobre el monto total invertido y distribuido en pagos trimestrales a lo largo del año. Este retorn
Buenas! Solo tengo una última pregunta, es correcto decir que se dará un 25% de la inversión en vez de un porcentaje de los beneficios acorde con el porcentaje de inversión?

2024-05-18 19:29 UTC, JuanluRM commented
Gracias por tu aportación, tras darle varias vueltas he decidido cambiarlo para que quede más claro, pero ten en cuenta que todo son estimaciones por lo que los numeros no son todo.

2024-05-18 19:33 UTC, pabpercab1 approved these changes
Perce que todo está correcto ahora. Gracias por el trabajo realizado!

2024-05-18 19:35 UTC, merged